Repository Automattic/vip-design-system, pull requests merged in 2023-11, with the labels that each got.

#290 Add Nav component with some Storybook configuration
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/system/Link/Link.stories.tsx
  src/system/Nav/Nav.stories.tsx
  src/system/Nav/Nav.test.tsx
  src/system/Nav/Nav.tsx
  src/system/Nav/NavItem.tsx
  src/system/Nav/index.tsx
  src/system/Tabs/Tabs.stories.jsx
  src/system/Wizard/Wizard.stories.tsx
  src/system/index.js
Labels: [Type] enhancement, [Status] Ready to Merge, [Pri] Normal

#294 PIE-3778 Make the Notice icon alignment adjust with the Notice content
  src/system/Notice/Notice.stories.tsx
  src/system/Notice/Notice.tsx
Labels: [Status] Ready to Merge

#295 Fix Radio buttons zIndex issue
  src/system/Form/Radio.js
Labels: [Type] Bug, [Status] Ready to Merge, [Pri] Normal

#298 Add new Toolbar component
  .storybook/decorators/withBoundingBox.tsx
  src/system/Avatar/Avatar.tsx
  src/system/Nav/Nav.stories.tsx
  src/system/Nav/Nav.test.tsx
  src/system/Nav/Nav.tsx
  src/system/Nav/NavItem.tsx
  src/system/Nav/index.tsx
  src/system/Nav/styles.ts
  src/system/Toolbar/Logo.tsx
  src/system/Toolbar/Toolbar.stories.tsx
  src/system/Toolbar/Toolbar.test.tsx
  src/system/Toolbar/Toolbar.tsx
  src/system/Toolbar/ToolbarUtilNav.tsx
  src/system/Toolbar/index.tsx
  src/system/index.js
  src/system/theme/breakpoints.ts
  src/system/theme/index.js
Labels: [Type] enhancement, [Status] Needs Review, [Pri] Normal

#300 Remove zIndex from main nav
  src/system/Nav/styles.ts
Labels: [Type] Bug, [Status] Needs Review

#310 [Toolbar] Set the 64px height only for 1047px breakpoint and above
  src/system/Toolbar/Toolbar.tsx
Labels: [Type] Bug, [Status] Needs Review, [Pri] Normal

#313 New components: Menu & Breadcrumbs
  package-lock.json
  package.json
  src/system/Breadcrumbs/Breadcrumbs.stories.tsx
  src/system/Breadcrumbs/Breadcrumbs.test.tsx
  src/system/Breadcrumbs/Breadcrumbs.tsx
  src/system/Breadcrumbs/styles.ts
  src/system/Button/Button.stories.tsx
  src/system/Link/Link.tsx
  src/system/Nav/Nav.stories.tsx
  src/system/Nav/Nav.test.tsx
  src/system/Nav/Nav.tsx
  src/system/Nav/NavItem.tsx
  src/system/Nav/NavItemGroup.tsx
  src/system/Nav/index.tsx
  src/system/Nav/styles.ts
  src/system/Toolbar/Toolbar.stories.tsx
  src/system/Tooltip/Tooltip.stories.tsx
  src/system/index.js
Labels: [Type] enhancement, [Status] Needs Review

#319 Fix Toolbar story with custom link
  src/system/Toolbar/Toolbar.stories.tsx
Labels: [Type] Documentation, [Status] Needs Review

#322 Update <Drawer /> with some adjustments
  src/system/Drawer/Drawer.stories.tsx
  src/system/Drawer/Drawer.test.tsx
  src/system/Drawer/Drawer.tsx
  src/system/Drawer/styles.ts
  src/system/index.js
Labels: [Type] enhancement, [Status] Needs Review

#328 Make Nav full-width by default
  src/system/Nav/Nav.stories.tsx
  src/system/Nav/styles.ts
Labels: [Type] enhancement, [Status] Needs Review
