Repository Automattic/vip-design-system, pull requests merged in 2023-02, with the labels that each got.

#178 Dark mode improvements - New batch
  src/system/Form/Input.js
  src/system/Form/Validation.js
  src/system/NewDialog/DialogOverlay.js
  src/system/Notice/Notice.js
  src/system/Notice/Notice.stories.jsx
  src/system/OptionRow/OptionRow.js
  src/system/OptionRow/OptionRow.stories.jsx
  src/system/theme/generated/valet-theme-dark.json
  src/system/theme/generated/valet-theme-light.json
  src/system/theme/index.js
  tokens/valet-core/wpvip-expressive-type.json
  tokens/valet-core/wpvip-productive-color-dark.json
  tokens/valet-core/wpvip-productive-color.json
Labels: [Status] Ready to Merge

#175 Add support for Wizard title autofocus when switching tabs
  src/system/Wizard/Wizard.js
  src/system/Wizard/Wizard.stories.jsx
  src/system/Wizard/WizardStep.js
Labels: [Status] Needs Review

#171 Show the selected value in the input of Form.Autocomplete
  src/system/NewForm/FormAutocomplete.js
  src/system/NewForm/FormAutocomplete.stories.jsx
Labels: do not merge

#184 Remove caps variant from table header
  src/system/Table/TableCell.js
  src/system/theme/textStyles.js
Labels: do not merge

#182 Update RadioBoxGroup component
  src/system/Form/RadioBoxGroup.js
  src/system/Form/RadioBoxGroup.stories.jsx
Labels: [Status] Needs Review

#186 Reset Form.Autocomplete input properly when the user clears the input
  src/system/NewForm/FormAutocomplete.js
Labels: [Status] Ready to Merge

#179 Autocomplete with Multiselect
  package.json
  src/system/NewForm/FormAutocompleteMultiselect.js
  src/system/NewForm/FormAutocompleteMultiselect.stories.jsx
  src/system/NewForm/FormAutocompleteMultiselect.test.js
  src/system/NewForm/index.js
Labels: [Status] Needs Review
