Repository Automattic/vip-design-system, pull requests merged in 2023-10, with the labels that each got.

#235 Miscellaneous TypeScript fixes and dependency updates
  .storybook/decorators/withBoundingBox.tsx
  .storybook/decorators/withColorMode.tsx
  .storybook/decorators/withThemeProvider.tsx
  .storybook/preview.ts
  package-lock.json
  package.json
  src/system/Box/Box.tsx
  src/system/OptionRow/OptionRow.test.js
  src/system/Text/Text.tsx
  test/fileMock.js
  test/fileMock.ts
  test/setupAfterEnv.js
  test/setupAfterEnv.ts
  test/setupTests.js
Labels: [Status] Needs Review

#239 Button > Disabled > Remove hover effect and lessen the opacity
  src/system/Button/Button.js
  src/system/Button/Button.stories.jsx
Labels: [Status] Needs Review

#248 TS migration: Moves spinner component to TS
  src/system/Spinner/Spinner.js
  src/system/Spinner/Spinner.stories.tsx
  src/system/Spinner/Spinner.test.tsx
  src/system/Spinner/Spinner.tsx
  src/system/Spinner/index.js
  src/system/Spinner/index.ts
Labels: [Status] Needs Review

#245 Convert the Accordion to Typescript
  src/system/Accordion/Accordion.stories.tsx
  src/system/Accordion/Accordion.test.tsx
  src/system/Accordion/Accordion.tsx
  src/system/Accordion/index.ts
Labels: [Status] Needs Review

#250 Converting Code component to TypeScript
  src/system/Code/Code.stories.jsx
  src/system/Code/Code.stories.tsx
  src/system/Code/Code.test.tsx
  src/system/Code/Code.tsx
  src/system/Code/index.js
  src/system/Code/index.ts
Labels: enhancement, [Status] Needs Review

#252 TS migration: Moves progress component to TS
  src/system/Progress/Progress.stories.tsx
  src/system/Progress/Progress.test.tsx
  src/system/Progress/Progress.tsx
  src/system/Progress/index.js
  src/system/Progress/index.ts
Labels: [Status] Needs Review

#251 Convert Wizard to Typescript
  src/system/Form/Checkbox.stories.tsx
  src/system/Form/Checkbox.tsx
  src/system/Form/Input.stories.tsx
  src/system/Form/Input.styles.ts
  src/system/Form/Input.tsx
  src/system/Form/Label.stories.tsx
  src/system/Form/Label.tsx
  src/system/Form/RequiredLabel.tsx
  src/system/Form/Validation.tsx
  src/system/NewForm/Fieldset.js
  src/system/NewForm/Fieldset.tsx
  src/system/NewForm/Form.js
  src/system/NewForm/Form.tsx
  src/system/NewForm/Legend.js
  src/system/NewForm/Legend.tsx
  src/system/Wizard/Wizard.js
  src/system/Wizard/Wizard.stories.tsx
  src/system/Wizard/Wizard.tsx
  src/system/Wizard/WizardStep.tsx
  src/system/Wizard/WizardStepHorizontal.js
  src/system/Wizard/index.js
  src/system/Wizard/index.ts
Labels: [Status] Needs Review

#283 [PIE-3778] Readjust the NoticeIcon
  src/system/Notice/Notice.tsx
Labels: [Status] Needs Review

#284 Documentation improvements
  README.md
  docs/CONTRIBUTING.md
Labels: [Type] Documentation
