Repository Automattic/vip-design-system, pull requests merged in 2024-03, with the labels that each got.

#350 Fix wrapping of items in toolbar util menu
  src/system/Nav/styles/variants/toolbar.ts
  src/system/Toolbar/Toolbar.stories.tsx
Labels: [Status] Needs Review

#354 Update Input Radio Component Styles + TypeScript conversion
  src/system/Form/Label.tsx
  src/system/Form/Radio.js
  src/system/Form/Radio.stories.jsx
  src/system/Form/Radio/Radio.stories.tsx
  src/system/Form/Radio/Radio.test.tsx
  src/system/Form/Radio/Radio.tsx
  src/system/Form/Radio/RadioOption.tsx
  src/system/Form/Radio/styles.ts
  src/system/Form/index.js
  src/system/theme/index.js
Labels: [Type] Documentation, [Type] enhancement, [Status] Needs Review

#355 Update Input Checkbox Component Styles and functionality
  package-lock.json
  package.json
  src/system/Form/Checkbox.stories.tsx
  src/system/Form/Checkbox.tsx
  src/system/Form/Checkbox/Checkbox.stories.tsx
  src/system/Form/Checkbox/Checkbox.test.tsx
  src/system/Form/Checkbox/Checkbox.tsx
  src/system/Form/Checkbox/styles.ts
  src/system/Form/Label.tsx
  src/system/Form/Radio/Radio.stories.tsx
  src/system/Form/Radio/Radio.tsx
  src/system/Form/Radio/styles.ts
  src/system/Form/index.js
Labels: [Type] Documentation, [Type] enhancement

#361 Adjust/checkbox radio styles
  src/system/Form/Checkbox/Checkbox.stories.tsx
  src/system/Form/Checkbox/Checkbox.tsx
  src/system/Form/Checkbox/styles.ts
  src/system/Form/Radio/Radio.stories.tsx
  src/system/Form/Radio/Radio.tsx
  src/system/Form/Radio/styles.ts
  src/system/Form/RadioBoxGroup.js
  src/system/theme/colors.js
Labels: [Status] Needs Review

#366 Remove special VIP border from the Avatar
  src/system/Avatar/Avatar.stories.tsx
  src/system/Avatar/Avatar.tsx
  src/system/Toolbar/Toolbar.stories.tsx
Labels: [Type] Documentation, [Type] enhancement, [Status] Needs Review

#367 Adjust checkbox/radio with indeterminate rules and less examples
  src/system/Form/Checkbox/Checkbox.stories.tsx
  src/system/Form/Checkbox/Checkbox.tsx
  src/system/Form/Checkbox/styles.ts
  src/system/Form/Radio/Radio.stories.tsx
Labels: [Status] Needs Review
